export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_REPOSITORY = 'CHANGE_REPOSITORY';
export const CHANGE_USER = 'CHANGE_USER';
export const CHANGE_UI_SHOWALL = 'CHANGE_UI_SHOWALL';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
